#!/usr/bin/python3
import sys
import PIL.Image

def loadrom(fp, nrom, msize):
	lout = []
	sbuf = ""
	st = 0

	fp.seek(0)
	for line in fp:
		line = line.strip()
		if st:
			if line.startswith("#"):
				st = 0
		if st:
			sbuf += line
			while len(sbuf) >= msize:
				lout.append(int(sbuf[:msize], 16))
				sbuf = sbuf[msize:]
	
		if line.startswith("#%d:" % nrom):
			st = 1
	return lout

if __name__ == "__main__":
	if len(sys.argv) < 2:
		sys.exit("usage: %s nxfile [bgrom] [chrom]" % sys.argv[0])
	else:
		fname = sys.argv[1]
	if len(sys.argv) > 2:
		bgrom = int(sys.argv[2])
	else:
		bgrom = 3
	if len(sys.argv) > 3:
		chrom = int(sys.argv[3])
	else:
		chrom = 2

	palrom = 1

	file = open(fname, "r")
	lpal = loadrom(file, palrom, 8)
	lchr = loadrom(file, chrom, 32)
	lbg = loadrom(file, bgrom, 2)

	if len(lpal) < 8:
		lpal = [
			0x053f2f00, 0x00383400,
			0x003c0c00, 0x003f3c00,
			0x003f2a15, 0x003f2a15,
			0x003f2a15, 0x003f2a15
		]

	lclr = []
	for npal, pal in enumerate(lpal):
		for nclr in range(4):
			rgb = pal >> (24 - nclr * 8) & 0xff
			if nclr == 0:
				if npal == 0:
					clr = rgb
				else:
					rgb = clr
			lclr.append((rgb >> 4 & 3) * 80 + 15)
			lclr.append((rgb >> 2 & 3) * 80 + 15)
			lclr.append((rgb      & 3) * 80 + 15)

	tsize = 8 + lbg[1] * 8
	img = PIL.Image.new("P", (lbg[2] * tsize, lbg[3] * tsize))
	img.putpalette(lclr)

	pixels = img.load()
	width, height = img.size

	sx = sy = 0
	for i, c in enumerate(lbg):
		if i < 4 or i % 2:
			continue

		for y in range(tsize):
			for x in range(tsize):
				ch = c
				dx, dy = 0, 0
				if x > 7:
					ch += 1
					dx += 8
				if y > 7:
					ch += 16
					dy += 8
				hi = lchr[ch] >> (x % 8 + y % 8 * 8) & 1
				lo = lchr[ch] >> (x % 8 + y % 8 * 8 + 64) & 1

				flp = lbg[i + 1] & 0x18
				pal = lbg[i + 1] & 0x07

				px = (lo | hi << 1) + pal * 4
				if flp == 0x00:
					pixels[7 - x % 8 + sx + dx, 7 - y % 8 + sy + dy] = px
				elif flp == 0x08:
					if tsize > 8:
						pixels[x % 8 + sx + 8 - dx, 7 - y % 8 + sy + dy] = px
					else:
						pixels[    x % 8 + sx + dx, 7 - y % 8 + sy + dy] = px
				elif flp == 0x10:
					if tsize > 8:
						pixels[7 - x % 8 + sx + dx, y % 8 + sy + 8 - dy] = px
					else:
						pixels[7 - x % 8 + sx + dx,     y % 8 + sy + dy] = px
				elif flp == 0x18:
					if tsize > 8:
						pixels[x % 8 + sx + 8 - dx, y % 8 + sy + 8 - dy] = px
					else:
						pixels[    x % 8 + sx + dx,     y % 8 + sy + dy] = px
		sx += tsize
		if sx >= width:
			sy += tsize
			sx = 0

	img.save(fname + ".png")
