#!/usr/bin/python3
import sys
import PIL.Image

defpal = [
	0x053f2f00, 0x00383400,
	0x003c0c00, 0x003f3c00,
	0x003f2a15, 0x003f2a15,
	0x003f2a15, 0x003f2a15
]

def loadrom(fp, nrom, mlen):
	lout = []
	sbuf = ""
	st = 0

	fp.seek(0)
	for line in fp:
		line = line.strip()
		if st:
			if line.startswith("#"):
				st = 0
		if st:
			sbuf += line
			while len(sbuf) >= mlen:
				lout.append(int(sbuf[:mlen], 16))
				sbuf = sbuf[mlen:]
	
		if line.startswith("#%d:" % nrom):
			st = 1
	return lout

def putbg8(bg, chr, im):
	pixels = im.load()
	width, height = im.size

	sx = sy = 0
	for i, c in enumerate(bg):
		if i < 4 or i % 2:
			continue

		for y in range(8):
			for x in range(8):
				hi = lchr[c] >> (x + y * 8) & 1
				lo = lchr[c] >> (x + y * 8 + 64) & 1

				flp = lbg[i + 1] & 0x18
				pal = lbg[i + 1] & 0x07

				px = (lo | hi << 1) + pal * 4
				if flp == 0x00:
					pixels[7 - x + sx, 7 - y + sy] = px
				elif flp == 0x08:
					pixels[    x + sx, 7 - y + sy] = px
				elif flp == 0x10:
					pixels[7 - x + sx,     y + sy] = px
				elif flp == 0x18:
					pixels[    x + sx,     y + sy] = px
		sx += 8
		if sx >= width:
			sy += 8
			sx = 0

def putbg16(bg, chr, im):
	pixels = im.load()
	width, height = im.size

	sx = sy = 0
	for i, c in enumerate(bg):
		if i < 4 or i % 2:
			continue

		for y in range(16):
			for x in range(16):
				ch = c
				dx, dy = 0, 0
				if x > 7:
					ch += 1
					dx = 8
				if y > 7:
					ch += 16
					dy = 8
				hi = lchr[ch] >> (x % 8 + y % 8 * 8) & 1
				lo = lchr[ch] >> (x % 8 + y % 8 * 8 + 64) & 1

				flp = lbg[i + 1] & 0x18
				pal = lbg[i + 1] & 0x07

				px = (lo | hi << 1) + pal * 4
				if flp == 0x00:
					pixels[7 - x % 8 + sx + dx, 7 - y % 8 + sy + dy] = px
				elif flp == 0x08:
					pixels[x % 8 + sx + 8 - dx, 7 - y % 8 + sy + dy] = px
				elif flp == 0x10:
					pixels[7 - x % 8 + sx + dx, y % 8 + sy + 8 - dy] = px
				elif flp == 0x18:
					pixels[x % 8 + sx + 8 - dx, y % 8 + sy + 8 - dy] = px
		sx += 16
		if sx >= width:
			sy += 16
			sx = 0

def putpal(pal, im):
	lclr = []
	for npal, p in enumerate(pal):
		for nclr in range(4):
			rgb = p >> (24 - nclr * 8) & 0xff
			if nclr == 0:
				if npal == 0:
					clr = rgb
				else:
					rgb = clr
			lclr.append((rgb >> 4 & 3) * 80 + 15)
			lclr.append((rgb >> 2 & 3) * 80 + 15)
			lclr.append((rgb      & 3) * 80 + 15)
	im.putpalette(lclr)

if __name__ == "__main__":
	if len(sys.argv) < 2:
		sys.exit("usage: %s nxfile [palidx] [palrom] [chrom] [bgrom]" % sys.argv[0])
	else:
		fname = sys.argv[1]
	if len(sys.argv) > 2:
		palidx = int(sys.argv[2])
	else:
		palidx = 0
	if len(sys.argv) > 3:
		palrom = int(sys.argv[3])
	else:
		palrom = 1
	if len(sys.argv) > 4:
		chrom = int(sys.argv[4])
	else:
		chrom = 2
	if len(sys.argv) > 5:
		bgrom = int(sys.argv[5])
	else:
		bgrom = 3

	file = open(fname, "r")
	lpal = loadrom(file, palrom, 8)
	lchr = loadrom(file, chrom, 32)
	lbg = loadrom(file, bgrom, 2)

	if len(lpal) < 8:
		lpal = defpal

	tsize = 8 + lbg[1] * 8
	img = PIL.Image.new("P", (lbg[2] * tsize, lbg[3] * tsize))

	putpal(lpal, img)
	if tsize == 8:
		putbg8(lbg, lchr, img)
	elif tsize == 16:
		putbg16(lbg, lchr, img)
	else:
		sys.exit("error: invalid cell size")

	img.save(fname + ".png")
