#!/usr/bin/python3
import sys
import PIL.Image

if len(sys.argv) < 2:
	sys.exit("usage: %s imagefile" % sys.argv[0])
else:
	fname = sys.argv[1]

img = PIL.Image.open(fname)
img = img.convert("P", dither=0, palette=1, colors=4)

pixels = img.load()
width, height = img.size

lchr = []

for sy in range(0, height, 8):
	for sx in range(0, width, 8):
		c = 0
		for y in range(8):
			for x in range(8):
				p = pixels[7 - x + sx, 7 - y + sy]
				c |= ((p & 1) << x + 64 | (p >> 1 & 1) << x) << y * 8
		lchr.append(c)

sys.stdout.write("#2:CHR\n")
for c in lchr:
	sys.stdout.write("%032X" % c)
sys.stdout.write("\n")
